// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQg69q7jAZyyBDkZaM8ntx9yUqJaMRwJA',
    appId: '1:433143664256:web:aae66d66975f242073a065',
    messagingSenderId: '433143664256',
    projectId: 'carrent-bd4ba',
    authDomain: 'carrent-bd4ba.firebaseapp.com',
    storageBucket: 'carrent-bd4ba.firebasestorage.app',
    measurementId: 'G-62K6VSP8NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA50EYAG7fJiJjoYwgkXt3WBZeNLvjWegw',
    appId: '1:433143664256:android:a8680e718764233273a065',
    messagingSenderId: '433143664256',
    projectId: 'carrent-bd4ba',
    storageBucket: 'carrent-bd4ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaSeGGMlK4_8ktMKckdrF8fA8szFGocns',
    appId: '1:433143664256:ios:a1316e9f6ba2f10873a065',
    messagingSenderId: '433143664256',
    projectId: 'carrent-bd4ba',
    storageBucket: 'carrent-bd4ba.firebasestorage.app',
    iosBundleId: 'com.techhubstudio.carrent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaSeGGMlK4_8ktMKckdrF8fA8szFGocns',
    appId: '1:433143664256:ios:a1316e9f6ba2f10873a065',
    messagingSenderId: '433143664256',
    projectId: 'carrent-bd4ba',
    storageBucket: 'carrent-bd4ba.firebasestorage.app',
    iosBundleId: 'com.techhubstudio.carrent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQg69q7jAZyyBDkZaM8ntx9yUqJaMRwJA',
    appId: '1:433143664256:web:7e0ab3ef01be131773a065',
    messagingSenderId: '433143664256',
    projectId: 'carrent-bd4ba',
    authDomain: 'carrent-bd4ba.firebaseapp.com',
    storageBucket: 'carrent-bd4ba.firebasestorage.app',
    measurementId: 'G-PY8LEYQ86Z',
  );
}
